spring.application.name=Ecom-webApp

spring.datasource.url=jdbc:postgresql://localhost:5432/Ecom
spring.datasource.username=postgres
spring.datasource.password=8524
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update